### ISSUE TITLE
NFM doesn't have the right attribute

### ISSUE THREAD

**Issue by zazzooo** [mcallaghan/text-as-data#8]
I have an issue in accessing the attribute of NFM. In particular, the `nfm.n_components_` and `nfm.components_`  one. 
I found two resources that refers to two different release of sklearn, version 1.1.3 (https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html), version 0.18.1 (http://www.devdoc.net/python/sklearn-0.18/modules/generated/sklearn.decomposition.NMF.html). I check the version of sklearn I am using, the code assures me that I am using the stable and version (1.1.3). I also printed the attribute that I can access, I attached the code and output:

`nmf = NMF(10)`
`print(nmf._n_features_out)`

output:

`['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_check_feature_names', '_check_n_features', '_check_params', '_check_w_h', '_fit_transform', '_get_param_names', '_get_tags', '_more_tags', '_n_features_out', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_scale_regularization', '_validate_data', 'alpha', 'alpha_H', 'alpha_W', 'beta_loss', 'fit', 'fit_transform', 'get_feature_names_out', 'get_params', 'init', 'inverse_transform', 'l1_ratio', 'max_iter', 'n_components', 'random_state', 'regularization', 'set_params', 'shuffle', 'solver', 'tol', 'transform', 'verbose']`

Second part of the output, error that raise:

` AttributeError                            Traceback (most recent call last)
Cell In [47], line 3
      1 nmf = NMF(10)
----> 2 nmf._n_features_out

File c:\Users\zazzo\.virtualenvs\Text_as_data-P4hExxh8\lib\site-packages\sklearn\decomposition\_nmf.py:1770, in NMF._n_features_out(self)
   1767 @property
   1768 def _n_features_out(self):
   1769     """Number of transformed output features."""
-> 1770     return self.components_.shape[0]

AttributeError: 'NMF' object has no attribute 'components_' `

It is clear that the wanted attributes are not in the list. More interesting, none of the class in the on-line documentation is the one I am currently running. 

Accessing those value is fundamental to complete the assignment 2, any help is much appreciated!

**Comment by mcallaghan** [comment]
Could it be because you have not yet fit the model? 
if you do
```
texts = [
    "Cats, elephants, camels",
    "Hawks doves pigeons",
    "Cats pigeons"
]
vec = CountVectorizer()
dfmat = vec.fit_transform(texts)
nmf.fit_transform(dfmat)
```

does this help?
